-- Migration 035: Taste Preferences & Learning System
-- Smart recommendation engine with user controls

-- User taste preferences and settings
CREATE TABLE IF NOT EXISTS user_taste_preferences (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  -- Learning settings (user controls)
  learning_enabled BOOLEAN DEFAULT TRUE,
  show_recommendations BOOLEAN DEFAULT TRUE,
  auto_import_enabled BOOLEAN DEFAULT FALSE,
  
  -- Preference data
  favorite_cuisines TEXT[], -- ['Italian', 'Mexican', 'Asian']
  disliked_cuisines TEXT[],
  favorite_ingredients TEXT[],
  disliked_ingredients TEXT[],
  preferred_difficulty VARCHAR(20) DEFAULT 'any', -- easy, medium, hard, any
  preferred_cook_time INTEGER, -- max minutes
  dietary_restrictions TEXT[], -- ['vegetarian', 'gluten-free', etc.]
  
  -- Taste profile (auto-learned)
  spice_level INTEGER DEFAULT 5, -- 1-10 scale
  sweetness_preference INTEGER DEFAULT 5,
  protein_preference VARCHAR(50), -- chicken, beef, fish, vegetarian
  meal_type_preference VARCHAR(50), -- breakfast, lunch, dinner
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  UNIQUE(user_id)
);

-- Recipe cooking frequency and ratings
CREATE TABLE IF NOT EXISTS recipe_routine_tracker (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  
  -- Frequency tracking
  times_cooked INTEGER DEFAULT 0,
  last_cooked_date TIMESTAMP,
  first_cooked_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  -- User feedback
  user_rating INTEGER CHECK (user_rating >= 1 AND user_rating <= 5),
  is_favorite BOOLEAN DEFAULT FALSE,
  would_make_again BOOLEAN,
  
  -- Routine patterns
  typical_day_of_week INTEGER, -- 0-6 (Sunday-Saturday)
  typical_meal_time VARCHAR(20), -- breakfast, lunch, dinner, snack
  average_days_between INTEGER, -- calculated from cooking history
  
  -- Notes
  personal_notes TEXT,
  modifications TEXT, -- user's recipe modifications
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  UNIQUE(user_id, recipe_id)
);

-- Recommended recipes (generated by system)
CREATE TABLE IF NOT EXISTS recipe_recommendations (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  recipe_id INTEGER NOT NULL REFERENCES recipes(id) ON DELETE CASCADE,
  
  -- Recommendation metadata
  recommendation_score DECIMAL(5,2), -- 0-100 confidence score
  recommendation_reason TEXT, -- why this was recommended
  recommendation_type VARCHAR(50), -- taste_match, routine_based, trending, seasonal
  
  -- User interaction
  viewed BOOLEAN DEFAULT FALSE,
  viewed_at TIMESTAMP,
  dismissed BOOLEAN DEFAULT FALSE,
  dismissed_at TIMESTAMP,
  added_to_collection BOOLEAN DEFAULT FALSE,
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP, -- recommendations can expire
  
  UNIQUE(user_id, recipe_id, created_at)
);

-- Recipe import history (from external websites)
CREATE TABLE IF NOT EXISTS recipe_import_history (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  recipe_id INTEGER REFERENCES recipes(id) ON DELETE SET NULL,
  
  -- Source information
  source_url TEXT NOT NULL,
  source_site VARCHAR(100), -- 'allrecipes.com', 'foodnetwork.com', etc.
  import_method VARCHAR(50), -- 'manual', 'auto', 'quick_add'
  
  -- Import status
  import_status VARCHAR(50) DEFAULT 'pending', -- pending, success, failed
  import_error TEXT,
  
  -- Scraped data (before conversion)
  raw_data JSONB,
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- User favorite meals/foods tracking
CREATE TABLE IF NOT EXISTS user_favorite_meals (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  meal_name VARCHAR(255) NOT NULL,
  meal_type VARCHAR(50), -- breakfast, lunch, dinner, snack, dessert
  cuisine_type VARCHAR(50),
  
  -- Why it's favorite
  reason TEXT,
  comfort_food BOOLEAN DEFAULT FALSE,
  special_occasion BOOLEAN DEFAULT FALSE,
  
  -- Linked recipe (if exists)
  recipe_id INTEGER REFERENCES recipes(id) ON DELETE SET NULL,
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  
  UNIQUE(user_id, meal_name)
);

-- Taste learning events (for ML/analytics)
CREATE TABLE IF NOT EXISTS taste_learning_events (
  id SERIAL PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  
  event_type VARCHAR(50) NOT NULL, -- recipe_cooked, recipe_rated, recipe_favorited, etc.
  event_data JSONB,
  
  -- What we learned
  learned_preference VARCHAR(100), -- 'likes_italian', 'prefers_quick_meals', etc.
  confidence_score DECIMAL(5,2),
  
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_taste_preferences_user ON user_taste_preferences(user_id);
CREATE INDEX IF NOT EXISTS idx_routine_tracker_user_recipe ON recipe_routine_tracker(user_id, recipe_id);
CREATE INDEX IF NOT EXISTS idx_routine_tracker_times_cooked ON recipe_routine_tracker(times_cooked DESC);
CREATE INDEX IF NOT EXISTS idx_recommendations_user ON recipe_recommendations(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_recommendations_score ON recipe_recommendations(recommendation_score DESC);
CREATE INDEX IF NOT EXISTS idx_import_history_user ON recipe_import_history(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_import_history_url ON recipe_import_history(source_url);
CREATE INDEX IF NOT EXISTS idx_favorite_meals_user ON user_favorite_meals(user_id);
CREATE INDEX IF NOT EXISTS idx_learning_events_user ON taste_learning_events(user_id, created_at DESC);

-- Function to update routine tracker when recipe is cooked
CREATE OR REPLACE FUNCTION update_recipe_routine()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO recipe_routine_tracker (user_id, recipe_id, times_cooked, last_cooked_date)
  VALUES (NEW.user_id, NEW.recipe_id, 1, NEW.cooked_at)
  ON CONFLICT (user_id, recipe_id) 
  DO UPDATE SET
    times_cooked = recipe_routine_tracker.times_cooked + 1,
    last_cooked_date = NEW.cooked_at,
    updated_at = CURRENT_TIMESTAMP;
  
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger on recipe_cooking_history
CREATE TRIGGER trigger_update_routine
AFTER INSERT ON recipe_cooking_history
FOR EACH ROW
EXECUTE FUNCTION update_recipe_routine();

-- Initialize taste preferences for existing users
INSERT INTO user_taste_preferences (user_id)
SELECT id FROM users
WHERE NOT EXISTS (
  SELECT 1 FROM user_taste_preferences WHERE user_id = users.id
)
ON CONFLICT (user_id) DO NOTHING;

COMMENT ON TABLE user_taste_preferences IS 'User taste preferences and learning settings';
COMMENT ON TABLE recipe_routine_tracker IS 'Tracks how often users cook each recipe';
COMMENT ON TABLE recipe_recommendations IS 'System-generated recipe recommendations';
COMMENT ON TABLE recipe_import_history IS 'History of recipes imported from external sites';
COMMENT ON TABLE user_favorite_meals IS 'User-defined favorite meals and foods';
COMMENT ON TABLE taste_learning_events IS 'Events for machine learning and analytics';
